-- MySQL Script generated by MySQL Workbench
-- Mon Sep 13 20:42:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema enemulado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enemulado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enemulado` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `enemulado` ;

-- -----------------------------------------------------
-- Table `enemulado`.`areaconhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`areaconhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NomeMateria` VARCHAR(45) NOT NULL,
  `id_AreaConhecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_AreaConhecimento` (`id_AreaConhecimento` ASC),
  CONSTRAINT `materia_ibfk_1`
    FOREIGN KEY (`id_AreaConhecimento`)
    REFERENCES `enemulado`.`areaconhecimento` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`questoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_questao` INT NOT NULL,
  `id_Materia` INT NOT NULL,
  `id_CorProva` VARCHAR(50) NOT NULL,
  `id_AnoProva` VARCHAR(50) NOT NULL,
  `id_instituicao` INT NOT NULL,
  `textoprincipal` VARCHAR(1650) NOT NULL,
  `textoquestao` VARCHAR(300) NOT NULL,
  `Img_Top` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Central` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Final` VARCHAR(500) NULL DEFAULT NULL,
  `alternativa_A` VARCHAR(500) NOT NULL,
  `alternativa_B` VARCHAR(500) NOT NULL,
  `alternativa_C` VARCHAR(500) NOT NULL,
  `alternativa_D` VARCHAR(500) NOT NULL,
  `alternativa_E` VARCHAR(500) NOT NULL,
  `gabarito` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_Materia` (`id_Materia` ASC),
  INDEX `id_instituicao` (`id_instituicao` ASC),
  CONSTRAINT `questoes_ibfk_1`
    FOREIGN KEY (`id_Materia`)
    REFERENCES `enemulado`.`materia` (`id`),
  CONSTRAINT `questoes_ibfk_4`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `enemulado`.`instituicao` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`tipo_simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_simulado` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`tipo_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `telefone` INT NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `id_tipo_cargo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) ,
  UNIQUE INDEX `cpf` (`cpf` ASC) ,
  INDEX `id_tipo_cargo` (`id_tipo_cargo` ASC) ,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_tipo_cargo`)
    REFERENCES `enemulado`.`tipo_cargo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`simulados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`simulados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_simulado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_inicio` INT NOT NULL,
  `data_final` INT NOT NULL,
  `duracao` INT NOT NULL,
  `nota_geral` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_tipo_simulado_idx` (`id_tipo_simulado` ASC) ,
  CONSTRAINT `id_tipo_simulado_q`
    FOREIGN KEY (`id_tipo_simulado`)
    REFERENCES `enemulado`.`tipo_simulado` (`id`),
  CONSTRAINT `simulados_aluno_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `enemulado`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `enemulado`.`simulado_questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`simulado_questao` (
  `id` INT NOT NULL,
  `id_questoes` INT NOT NULL,
  `id_simulado` INT NOT NULL,
  `resposta_usuario` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_simulado_idx` (`id_simulado` ASC) ,
  INDEX `id_questoes_idx` (`id_questoes` ASC) ,
  CONSTRAINT `id_questoes`
    FOREIGN KEY (`id_questoes`)
    REFERENCES `enemulado`.`questoes` (`id`),
  CONSTRAINT `id_simulado`
    FOREIGN KEY (`id_simulado`)
    REFERENCES `enemulado`.`simulados` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- codigo limpo, sem configuração do banco

-- -----------------------------------------------------
-- Table `enemulado`.`areaconhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`areaconhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NomeMateria` VARCHAR(45) NOT NULL,
  `id_AreaConhecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_AreaConhecimento` (`id_AreaConhecimento` ASC),
  CONSTRAINT `materia_ibfk_1`
    FOREIGN KEY (`id_AreaConhecimento`)
    REFERENCES `enemulado`.`areaconhecimento` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`questoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_questao` INT NOT NULL,
  `id_Materia` INT NOT NULL,
  `id_CorProva` VARCHAR(50) NOT NULL,
  `id_AnoProva` VARCHAR(50) NOT NULL,
  `id_instituicao` INT NOT NULL,
  `textoprincipal` VARCHAR(1650) NOT NULL,
  `textoquestao` VARCHAR(300) NOT NULL,
  `Img_Top` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Central` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Final` VARCHAR(500) NULL DEFAULT NULL,
  `alternativa_A` VARCHAR(500) NOT NULL,
  `alternativa_B` VARCHAR(500) NOT NULL,
  `alternativa_C` VARCHAR(500) NOT NULL,
  `alternativa_D` VARCHAR(500) NOT NULL,
  `alternativa_E` VARCHAR(500) NOT NULL,
  `gabarito` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_Materia` (`id_Materia` ASC),
  INDEX `id_instituicao` (`id_instituicao` ASC),
  CONSTRAINT `questoes_ibfk_1`
    FOREIGN KEY (`id_Materia`)
    REFERENCES `enemulado`.`materia` (`id`),
  CONSTRAINT `questoes_ibfk_4`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `enemulado`.`instituicao` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`tipo_simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_simulado` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`tipo_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));




-- -----------------------------------------------------
-- Table `enemulado`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `telefone` INT NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `id_tipo_cargo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) ,
  UNIQUE INDEX `cpf` (`cpf` ASC) ,
  INDEX `id_tipo_cargo` (`id_tipo_cargo` ASC) ,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_tipo_cargo`)
    REFERENCES `enemulado`.`tipo_cargo` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`simulados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`simulados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_simulado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_inicio` INT NOT NULL,
  `data_final` INT NOT NULL,
  `duracao` INT NOT NULL,
  `nota_geral` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) ,
  INDEX `id_tipo_simulado_idx` (`id_tipo_simulado` ASC) ,
  CONSTRAINT `id_tipo_simulado_q`
    FOREIGN KEY (`id_tipo_simulado`)
    REFERENCES `enemulado`.`tipo_simulado` (`id`),
  CONSTRAINT `simulados_aluno_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `enemulado`.`usuario` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`simulado_questao`
-- -----------------------------------------------------





-- -----------------------------------------------------
-- Table `enemulado`.`areaconhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`areaconhecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_area` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`instituicao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NomeMateria` VARCHAR(45) NOT NULL,
  `id_AreaConhecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_AreaConhecimento` (`id_AreaConhecimento` ASC),
  CONSTRAINT `materia_ibfk_1`
    FOREIGN KEY (`id_AreaConhecimento`)
    REFERENCES `enemulado`.`areaconhecimento` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`questoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`questoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_questao` INT NOT NULL,
  `id_Materia` INT NOT NULL,
  `id_CorProva` VARCHAR(50) NOT NULL,
  `id_AnoProva` VARCHAR(50) NOT NULL,
  `id_instituicao` INT NOT NULL,
  `textoprincipal` VARCHAR(1650) NOT NULL,
  `textoquestao` VARCHAR(300) NOT NULL,
  `Img_Top` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Central` VARCHAR(500) NULL DEFAULT NULL,
  `Img_Final` VARCHAR(500) NULL DEFAULT NULL,
  `alternativa_A` VARCHAR(500) NOT NULL,
  `alternativa_B` VARCHAR(500) NOT NULL,
  `alternativa_C` VARCHAR(500) NOT NULL,
  `alternativa_D` VARCHAR(500) NOT NULL,
  `alternativa_E` VARCHAR(500) NOT NULL,
  `gabarito` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_Materia` (`id_Materia` ASC),
  INDEX `id_instituicao` (`id_instituicao` ASC),
  CONSTRAINT `questoes_ibfk_1`
    FOREIGN KEY (`id_Materia`)
    REFERENCES `enemulado`.`materia` (`id`),
  CONSTRAINT `questoes_ibfk_4`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `enemulado`.`instituicao` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`tipo_simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_simulado` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`tipo_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`tipo_cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));




-- -----------------------------------------------------
-- Table `enemulado`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `telefone` INT NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `id_tipo_cargo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) ,
  UNIQUE INDEX `cpf` (`cpf` ASC) ,
  INDEX `id_tipo_cargo` (`id_tipo_cargo` ASC) ,
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_tipo_cargo`)
    REFERENCES `enemulado`.`tipo_cargo` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`simulados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`simulados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_simulado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `data_inicio` INT NOT NULL,
  `data_final` INT NOT NULL,
  `duracao` INT NOT NULL,
  `nota_geral` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC) ,
  INDEX `id_tipo_simulado_idx` (`id_tipo_simulado` ASC) ,
  CONSTRAINT `id_tipo_simulado_q`
    FOREIGN KEY (`id_tipo_simulado`)
    REFERENCES `enemulado`.`tipo_simulado` (`id`),
  CONSTRAINT `simulados_aluno_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `enemulado`.`usuario` (`id`));



-- -----------------------------------------------------
-- Table `enemulado`.`simulado_questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enemulado`.`simulado_questao` (
  `id` INT NOT NULL,
  `id_questoes` INT NOT NULL,
  `id_simulado` INT NOT NULL,
  `resposta_usuario` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_simulado_idx` (`id_simulado` ASC) ,
  INDEX `id_questoes_idx` (`id_questoes` ASC) ,
  CONSTRAINT `id_questoes`
    FOREIGN KEY (`id_questoes`)
    REFERENCES `enemulado`.`questoes` (`id`),
  CONSTRAINT `id_simulado`
    FOREIGN KEY (`id_simulado`)
    REFERENCES `enemulado`.`simulados` (`id`))